version: 0.2

phases:
  build:
    commands:
      - start_time=`date +%s`
      - chmod +x ./scripts/build.sh && ./scripts/build.sh $SOLUTION_NAME $BUILD_OUTPUT_BUCKET $BUILD_OUTPUT_REGION
      - echo "Build completed" $start_time
artifacts:
  files:
    - cloudformation/**/*
    - iam/**/*
    - metadata/**/*
    - src/**/*
    - docs/**/*
    - scripts/**/*
    - README.md
    - .viperlightignore
    - .viperlightrc
